<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<SpaRoot>..\griddata.client</SpaRoot>
		<SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
		<SpaProxyServerUrl>https://localhost:5444</SpaProxyServerUrl>
	</PropertyGroup>
</Project>
